name: GitHub Workflow Assessment CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: orderservice
  REGISTRY: ghcr.io/kuzeal/orderservice:local

jobs:
  format-and-test:
    if: ${{ !inputs.redeploy_only }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Dotnet v4
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Cache
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: nuget-${{ hashFiles('**/*.csproj')}}
    - run: dotnet format --verify-no-changes
    - run: dotnet format build -c Release
    - run: dotnet test
    - run: dotnet list package --vulnerable --include-transitive

