name: GitHub Workflow Assessment CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: orderservice
  REGISTRY: ghcr.io/kuzeal

jobs:
  format-and-test:
    if: ${{ !inputs.redeploy_only }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Dotnet v4
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Cache
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: nuget-${{ hashFiles('**/*.csproj')}}
    - run: dotnet format OrderService --verify-no-changes
    - run: dotnet build OrderService -c Release
    - run: dotnet test OrderService
    - run: dotnet list OrderService package --vulnerable --include-transitive

  docker-build-and-scan:
    if: ${{ !inputs.redeploy_only }}
    needs: format-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          load: true
          cache-from: type-gha
          cache-to: type=gha,mode=max
      - uses: aquasecurity/trivy-action@master
        with:
          image:ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '1'
